default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: expert_search_development

test:
  <<: *default
  database: expert_search_test

production:
  <<: *default
  database: expert_search_production
  username: expert_search
  password: <%= ENV['expert_search_DATABASE_PASSWORD'] %>
